### ISSUE TITLE
Bewerbung auch nachträglich ermöglichen

### ISSUE THREAD

**Issue by user80333Q** [schillermann/trolleydienst#1]
Bewerbungen auch zulassen wenn die Schicht bereits mit 2 oder 3 Verkündigern (eigentlich) gebucht ist.

So können kurzzeitige Krankheitsausfälle oder von den Verkündigern abgesprochene Änderungen einfacher realisiert werden.

**Comment by schillermann** [comment]
In der neuen Version kann pro Schichtart die maximale Anzahl der Teilnehmer angegeben werden, siehe trolleydienst.de
