### ISSUE TITLE
SQL Injections

### ISSUE THREAD

**Issue by ream88** [schillermann/trolleydienst#1]
Hab mal drüber geschaut und gesehen, dass der Code potenziell für SQL Injections gefährdet ist, und so nicht auf einem Live System installiert werden sollte!

Bei Fragen bitte melden :)

**Comment by schillermann** [comment]
Mensch bist du schnell beim Durchsichten des Codes.
Bin gerade dabei das auf PDO umzustellen.
Siehe hier: [branch switch-to-pdo](https://github.com/schillermann/trolleydienst/blob/switch-to-pdo/index.php)

Danke dir für den Hinweis.
Weiter so :-)

**Comment by ream88** [comment]
Ja Berufskrankheit 😜 PDO is schon mal ein erster guter Schritt. Wobei ich dir aus Erfahrung sagen kann, dass du vielleicht auf ein Framework setzen solltest. Einfach um gewisse Konventionen einzuhalten und nicht alles neu entwickeln musst. [Laravel](https://laravel.com/) hat sich als sehr Einsteiger freundlich erwiesen, und macht auch sehr gute Abstraktionen (MVC)! 😊

**Comment by schillermann** [comment]
Danke für deine Tipps.
Ziel ist es das Tool so einfach wie möglich zu halten um anderen die das Tool nutzen das Ändern so leicht wie möglich zu gestalten. Daher hatte ich ein Framework bis jetzt noch nicht ins Auge gefasst.
Laravel ist sehr einfach gehalten bzgl. des Datenbank Handlings.
Aber auch Symfony hat seine Vorzüge, z.B. das Erstellen von Entities als Class.
Ich werde mir nochmal Gedanken darum machen ob es Sinn macht hier eines der beiden Frameworks einzusetzen, oder doch kein Framework.

Ideen sind immer willkommen.

**Comment by ream88** [comment]
Wichtig ist das du nicht einfach mit potentiell gefährlich verwechselt! Du darfst nicht vergessen, dass deine "Kundschaft" nicht so versiert ist, und darauf vertraut dass die Software keine Sicherheitslücken hat. Und deswegen finde ich Open Source Frameworks sollten die Grundlage von jedem Projekt sein. Vielleicht hilft dir das! 😉

**Comment by schillermann** [comment]
Da hast du vollkommen recht.
Das ist ein sehr gutes Argument.
Jetzt ist nur die Frage ob Laravel oder Symfony eingesetzt werden sollte.
Wie sind deine Erfahrungswerte hierbei um die Anwendung simpel zu halten?

**Comment by schillermann** [comment]
Da Symfony pupulärer ist habe ich mich für dieses Framework nun entschieden.
Schrittweise werde ich das Tool daraufhin anpassen.
[Siehe commit](https://github.com/schillermann/trolleydienst/commit/5f186a79b428c1f8065d1fa456f831cadb3262f6)

**Comment by ream88** [comment]
Gefällt mir 😊
