### ISSUE TITLE
Änderungsprotokoll

### ISSUE THREAD

**Issue by user80333Q** [schillermann/trolleydienst#2]
Datum & Uhrzeit in allen Datenbanktabellen für Änderungen an den Daten mitführen.

Ermöglicht bessere Nachvollziehbarkeit - z.B. hat Verkündiger Passwort selbst geändert, wenn ja, wann.

**Comment by schillermann** [comment]
Das Änderungsdatum wird in der neuen Version wird mitgespeichert. Siehe trolleydienst.de
