### ISSUE TITLE
Konfigurierbarer Benutzername (Einstellbarkeit wieviel Stellen)

### ISSUE THREAD

**Issue by user80333Q** [schillermann/trolleydienst#4]
Bisher wird der Benutzername wie folgt gebildet:

VvNn oder manuell. Die Einstellung für nur 2 Stellen Vorname und 2 Stellen Nachname hat sich im Standard als nicht besonders praktisch erwiesen. Wir benutzen inzwischen 3 Stellen oder manuelle noch längere Benutzernamen.

**Comment by schillermann** [comment]
Das neue Trolleydienst Tool ist draussen.
Du kannst es hier https://trolleydienst.de/ herunterladen.
Es gibt dort auch eine Demo Version.
Würde mich über Feedback freuen.

Das Repository habe ich nach https://github.com/trolleydienst/trolleydienst-php verschoben.

**Comment by schillermann** [comment]
In der neuen Version wird nur noch mit dem realen Namen gearbeitet.
Ein Benutzername gibt es nicht mehr, da sehr oft der Benutzername vergessen wurde.

**Comment by user80333Q** [comment]
Die neue Anmeldung über "Name" ist sicherlich auch nicht verkehrt, führ jetzt aber wieder zu einer Umstellung vom alten System. Ich fand die Variante mit dem Benutzernamen auch nicht schlecht - das hätte ja auch die Möglichkeit geboten das auch noch änderbar zu gestalten um z.B. einen anderen für den Verkündiger sonst üblichen Benutzernamen selbst zu definieren wie er auch bei anderen Systemen schon verwendet wird.

**Comment by schillermann** [comment]
Ja da hast du recht. Jedoch birgt jede neu Funktion die Gefahr nicht damit zurecht zu kommen. Ein älterer Bruder z.B. konnte beim anlegen der Teilnehmer nicht wirklich was mit den vorgeschlagenen Benutzernamen anfangen. Es hatte ihn eher verwirrt. Aber jeder Admin ist anders :-)

**Comment by user80333Q** [comment]
Das stimmt, ich hatte bisher 2 Verkündiger von 60 Logins die mal nicht mehr rein kamen weil es Probleme beim Benutzernamen gab. Alles eine Sache der richtigen Einstellung und Hilfe ist ja da.

**Comment by schillermann** [comment]
Überall im ganzen Programm wurde bereits der reale Name des Verkündigers verwendet, nur für den Login wurde der Benutzername verwendet. Das hat zur Folge das man den Benutzernamen schnell vergisst.

**Comment by user80333Q** [comment]
Der reale Name macht leider trotzdem Probleme, doppelte gibt es leider trotzdem (bleibt bei grossen Familien nicht aus wenn mehr als eine Versammlung beteiligt ist) - ausserdem ist der Benutzername dadurch leider sehr lange bei der Eingabe. Bin von einigen angesprochen denen es gefühlt zu "umständlich" ist. Die allermeisten anderen Dienste haben ja abweichend einen selbst vergebenen Benutzernamen oder arbeiten mit der Mailadresse, manche wollten entweder ihren Google-Benutzer oder das Login sogar gleichlautend wie das jw.org Konto definieren.

**Comment by schillermann** [comment]
Danke dir für dein Feedback.
Solche Informationen sind sehr wertvoll um das Programm in die richtige Richtung zu entwickeln.
Ich werde das Programm so schnell wie möglich auf einen Benutzernamen hin anpassen.

**Comment by trolleydienst** [comment]
Ich habe dir ein Update erstellt.
Du kannst dir die Version 1.6.0 von der trolleydienst.de Website herunter laden.
Die alten Dateien kannst du überschreiben oder vor dem Hochladen löschen.
Die Dateien config.php und database.sqlite müssen bleiben.
Zur Sicherheit solltest du dir ein Backup erstellen.
Wenn du die neue Version hoch geladen hast, führe bitte die update.php aus.
Dadurch wird deine Datenbank auf den aktuellen Stand angepasst.
Der Benutzername wird mit dem Namen der Teilnehmer erstellt.
Nach dem Update kannst du die Benutzernamen nach Wunsch noch anpassen.

Reicht dir die Ansicht mit der Teilnehmer Liste aus?
Wenn du noch weitere Anregungen hast, immer her damit.
