### ISSUE TITLE
Teilnehmer - im Standard nur aktive anzeigen

### ISSUE THREAD

**Issue by user80333Q** [schillermann/trolleydienst#5]
Über Checkbox sollten im Standard nur die als "Aktiv" gekennzeichneten Verkündiger angezeigt werden.

Wir haben relativ viel Fluktuation auf der Plattform durch Verkündiger / Teilnehmer der SKE Schule, diese sind i.d.R. nur 8 Wochen bei uns, tauchen jedoch in der Liste weiterhin auf.

Auf Datenbank-Basis löschen geht zwar auch, ist aber nicht die sauberste Lösung (Bezug zu den zurückliegenden geplanten Schichten fehlt ja dann).

**Comment by schillermann** [comment]
In der neuen Version kannst du die Teilnehmer nun löschen, siehe trolleydienst.de
