### ISSUE TITLE
Mailform

### ISSUE THREAD

**Issue by user80333Q** [schillermann/trolleydienst#6]
Der HTML-Code aus der mail.php wird oft beim Empfänger nicht ordentlich interpretiert. Anders / besser lösbar?

**Comment by schillermann** [comment]
In der aktuellen Version wird nur Text versendet kein HTML.
Scheinbar hast du noch eine ältere Version.
Die aktuellste Version kannst du hier herunter laden: https://github.com/schillermann/trolleydienst/archive/master.zip

Danke dir für die vielen Hinweise die du mir noch geschickt hattest.
Ich habe sie mit in meine Liste aufgenommen.
Einiges ist bereits in der Version umgesetzt die demnächst online geht.
